// kimono/src/general/SignUp.tsx
import React, {useCallback, useState} from "react";
import Alert from "react-bootstrap/Alert";
import Button from "react-bootstrap/Button";
import Card from "react-bootstrap/Card";
import Col from "react-bootstrap/Col";
import Container from "react-bootstrap/Container";
import Stack from "react-bootstrap/esm/Stack";
import Form from "react-bootstrap/Form";
import Row from "react-bootstrap/Row";
import {Link} from "react-router-dom";
import tatami from "../services/tatami.ts";
import ButtonSpinnerIf from "./ButtonSpinnerIf.tsx";

export default function SignUp() {

    const [email, setEmail] = useState("");
    const [username, setUsername] = useState("");
    const [password, setPassword] = useState("");

    const [signUp, {isLoading, error}] = tatami.endpoints.signUp.useLazyQuery();

    console.log(error);

    const submit = useCallback((e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        signUp({email: email, username: username, password: password});
    }, [signUp, email, username, password]);

    return (
        <Container>

            <Row className="justify-content-center mt-lg-3">
                <Col xs md="8" lg="6" xl="5" xxl="4">
                    <Form className="p-sm-2" noValidate onSubmit={submit}>

                        {error ? (
                            <Alert variant="danger">
                                <div className="text-danger">Signup Failed</div>
                                <div className="small text-muted">
                                    {error?.status
                                        ? `${error.status} `
                                        : null}
                                    {error?.data?.reason
                                        ? `${error?.data?.reason}`
                                        : null}
                                    &nbsp;
                                    {isLoading ? "Retrying..." : null}
                                </div>
                            </Alert>
                        ) : null}

                        <Card className="my-2 my-sm-4" bg="dark">

                            <Card.Header>
                                <Card.Title>
                                    Sign Up
                                </Card.Title>
                                <Card.Subtitle className="text-muted">
                                    Create a new account
                                </Card.Subtitle>
                            </Card.Header>

                            <Card.Body>
                                <div className="p-sm-2">

                                    <Form.Group className="mb-3" controlId="email">
                                        <Form.Label id="email-label">Email</Form.Label>
                                        <Form.Control
                                            aria-describedby="email-label"
                                            disabled={isLoading}
                                            type="email"
                                            value={email}
                                            onChange={(e) => setEmail(e.target.value)}
                                        />
                                    </Form.Group>

                                    <Form.Group className="mb-3" controlId="username">
                                        <Form.Label id="username-label">Username</Form.Label>
                                        <Form.Control
                                            aria-describedby="username-label"
                                            disabled={isLoading}
                                            type="text"
                                            value={username}
                                            onChange={(e) => setUsername(e.target.value)}
                                        />
                                    </Form.Group>

                                    <Form.Group className="mb-4" controlId="password">
                                        <Form.Label id="password-label">Password</Form.Label>
                                        <Form.Control
                                            aria-describedby="password-label"
                                            disabled={isLoading}
                                            type="password"
                                            value={password}
                                            onChange={(e) => setPassword(e.target.value)}
                                        />
                                    </Form.Group>

                                </div>
                            </Card.Body>

                            <Card.Footer>
                                <Stack gap={2} direction="horizontal">
                                    <Button
                                        aria-label="Create Account"
                                        disabled={isLoading}
                                        type="submit"
                                        variant="primary"
                                        className="ms-auto"
                                    >
                                        <ButtonSpinnerIf isLoading={isLoading}>
                                            Create Account
                                        </ButtonSpinnerIf>
                                    </Button>
                                </Stack>
                            </Card.Footer>

                        </Card>
                    </Form>
                </Col>
            </Row>

            <Row className="justify-content-center mt-3 mb-5">
                <Col className="text-center text-muted">
                    Already got an account? <Link to="/log-in">Log in</Link>
                </Col>
            </Row>

        </Container>
    );
}

// gyoza/src/routes/(anonymous)/sign-up/+page.svelte
<script lang="ts">
    import Alert from "$lib/Alert.svelte";
    import {signUpMutation} from "$lib/backend";
    import InputFeedback from "$lib/InputFeedback.svelte";
    import {useQueryClient} from "@tanstack/svelte-query";
    import {slide} from "svelte/transition";

    const signUp = signUpMutation(useQueryClient());

    let email = "";
    let username = "";
    let password = "";

    function handleSubmit(e: SubmitEvent) {
        e.preventDefault();
        e.stopPropagation();
        $signUp.mutate({email, username, password});
    }

    $: if ($signUp.isSuccess) {
        if ($signUp?.data?.status == "ok") {
            window.location.href = "/";
        }
    }
</script>

<svelte:head>
    <title>Sign Up</title>
    <meta name="description" content="Sign up for a new account">
</svelte:head>

<!-- svelte-ignore a11y-autofocus -->
<main class="flex flex-col max-w-sm mx-auto mt-10 px-3">
    {#if $signUp.error && $signUp.error.status !== 400}
        <div class="pb-4" transition:slide>
            <Alert class="alert-error" error={$signUp.error} head="Signup Failed" />
        </div>
    {/if}
    <form class="card" on:submit={handleSubmit}>
        <div class="card-head py-3 px-4 text-xl">
            <h1>Sign Up</h1>
        </div>
        <div class="py-5 px-6 flex flex-col gap-4">
            <label class="form-control">
                <div class="label">
                    Email
                </div>
                <input
                    class="input input-sm"
                    name="email"
                    type="text"
                    bind:value={email}
                    autofocus
                />
                <InputFeedback field="email" error={$signUp.error} />
            </label>
            <label class="form-control">
                <div class="label">
                    Username
                </div>
                <input
                    class="input input-sm"
                    name="username"
                    type="text"
                    bind:value={username}
                />
                <InputFeedback field="username" error={$signUp.error} />
            </label>
            <label class="form-control">
                <div class="label">
                    Password
                </div>
                <input
                    class="input input-sm"
                    name="password"
                    type="password"
                    bind:value={password}
                />
                <InputFeedback field="password" error={$signUp.error} />
            </label>
        </div>
        <div class="card-foot py-3 px-4 mt-3 flex">
            <button class="ms-auto btn btn-primary">Sign up</button>
        </div>
    </form>
    <div class="pt-12 text-center text-gray-400">
        Already got an account?
        <a href="/log-in" class="text-primary link-hover"> Log in here </a>
    </div>
</main>

<style lang="postcss">
    input[type] {
        @apply w-full;
    }
</style>
