// yakitori/src/app/(anonymous)/log-in/page.tsx
"use client";

import {FormAlert} from "@/form/FormAlert";
import SpinnerIf from "@/general/SpinnerIf";
import backend from "@/services/backend";
import {faRightToBracket} from "@fortawesome/free-solid-svg-icons";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import Link from "next/link";
import React, {useCallback, useState} from "react";
import {Button, Card, Col, Container, Form, Row, Stack} from "react-bootstrap";

export default function LogIn() {
    const [usernameOrEmail, setUsernameOrEmail] = useState("");
    const [password, setPassword] = useState("");

    const [logIn, {isLoading, isError, error}] =
        backend.endpoints.logIn.useLazyQuery();

    const submit = useCallback(
        (e: React.FormEvent<HTMLFormElement>) => {
            e.preventDefault();
            logIn({username_or_email: usernameOrEmail, password: password});
        },
        [logIn, usernameOrEmail, password],
    );

    return (
        <Container>
            <Row className="justify-content-center mt-lg-3">
                <Col xs md="8" lg="6" xl="5" xxl="4">
                    <Form className="pt-2 p-sm-2" noValidate onSubmit={submit}>
                        {isError || (isLoading && error) ? (
                            <FormAlert
                                title="Login Failed"
                                error={error}
                                isLoading={isLoading}
                            />
                        ) : null}

                        <Card className="my-2 my-sm-4" bg="dark">
                            <Card.Header>
                                <Card.Title>Log In</Card.Title>
                            </Card.Header>

                            <Card.Body>
                                <div className="p-sm-2">
                                    <Form.Group
                                        className="mb-3"
                                        controlId="username_or_email"
                                    >
                                        <Form.Label id="identity-label">
                                            Username{" "}
                                            <span className="text-secondary small">
                                                or Email
                                            </span>
                                        </Form.Label>
                                        <Form.Control
                                            arial-describedby="identity-label"
                                            disabled={isLoading}
                                            type="text"
                                            value={usernameOrEmail}
                                            onChange={(e) =>
                                                setUsernameOrEmail(
                                                    e.target.value,
                                                )
                                            }
                                            autoFocus={true}
                                        />
                                    </Form.Group>

                                    <Form.Group
                                        className="mb-4"
                                        controlId="password"
                                    >
                                        <Form.Label id="password-label">
                                            Password
                                        </Form.Label>
                                        <Form.Control
                                            arial-describedby="password-label"
                                            disabled={isLoading}
                                            type="password"
                                            value={password}
                                            onChange={(e) =>
                                                setPassword(e.target.value)
                                            }
                                        />
                                    </Form.Group>
                                </div>
                            </Card.Body>

                            <Card.Footer>
                                <Stack gap={2} direction="horizontal">
                                    <Button
                                        arial-label="Log In"
                                        type="submit"
                                        variant="primary"
                                        className="ms-auto"
                                        disabled={isLoading}
                                    >
                                        <SpinnerIf isLoading={isLoading}>
                                            <FontAwesomeIcon
                                                icon={faRightToBracket}
                                                className="me-1"
                                            />
                                            Log in
                                        </SpinnerIf>
                                    </Button>
                                </Stack>
                            </Card.Footer>
                        </Card>
                    </Form>
                </Col>
            </Row>

            <Row className="justify-content-center mt-3 mb-5">
                <Col className="text-center text-secondary">
                    New to Izakaya?{" "}
                    <Link href="/sign-up">Create an account</Link>
                </Col>
            </Row>
        </Container>
    );
}

// gyoza/src/routes/(anonymous)/log-in/+page.svelte
<script lang="ts">
    import Alert from "$lib/Alert.svelte";
    import {logInMutation} from "$lib/backend";
    import {useQueryClient} from "@tanstack/svelte-query";
    import {slide} from "svelte/transition";

    const logIn = logInMutation(useQueryClient());

    let username_or_email = "";
    let password = "";

    function handleSubmit(e: SubmitEvent) {
        e.preventDefault();
        e.stopPropagation();
        $logIn.mutate({username_or_email, password});
    }

    $: if ($logIn.isSuccess) {
        if ($logIn?.data?.status == "ok") {
            window.location.href = "/";
        }
    }
</script>

<svelte:head>
    <title>Log In</title>
    <meta name="description" content="Log in to your Izakaya account" />
</svelte:head>

<!-- svelte-ignore a11y-autofocus -->
<main class="flex flex-col max-w-sm mx-auto mt-10 px-3">
    {#if $logIn.error}
        <div class="pb-4" transition:slide>
            <Alert error={$logIn.error} color="red" head="Login Failed" />
        </div>
    {/if}
    <form class="card" on:submit={handleSubmit}>
        <div class="card-head py-3 px-4 text-xl">
            <h1>Log In</h1>
        </div>
        <div class="card-body py-5 px-6 flex flex-col gap-4">
            <label>
                Username <span class="text-sm text-zinc-400">or Email</span>
                <input name="username_or_email" type="text" bind:value={username_or_email} autofocus />
            </label>
            <label>
                Password
                <input name="password" type="password" bind:value={password} />
            </label>
        </div>
        <div class="card-foot py-3 px-4 mt-3 flex">
            <button class="ms-auto btn btn-purple">Log in</button>
        </div>
    </form>
    <div class="pt-12 text-center text-gray-400">
        New to Izakaya?
        <a href="/sign-up" class="text-purple-400"> Create an account </a>
    </div>
</main>
