// kimono/src/general/About.tsx
import Container from "react-bootstrap/Container";
import Stack from "react-bootstrap/Stack";
import useTitle from "./useTitle.ts";

import svgPurpleHeart from "/purple-heart.svg";

export function About() {
    useTitle("About");
    return (
        <Container className="py-3">

            <Stack gap={3}>

                <div>
                    <div>
                        What is this website?&nbsp;
                        <a href="https://github.com/ruksi/ryokan">TL;DR: a Rust+React example project</a>
                    </div>
                    <div>
                        Made with
                        <div className="d-inline-block mx-1" style={{width: "1.5rem", height: "auto"}}>
                            <img src={svgPurpleHeart} alt="love" title="love"/>
                        </div>
                        by <a href="https://ruk.si/">Ruksi</a>
                    </div>
                    <div>
                        License: <a href="https://github.com/ruksi/ryokan/blob/main/LICENSE">MIT</a>
                    </div>
                </div>

                <div>
                    <div className="text-body-emphasis">
                        Multicolor emojis by <a href="https://openmoji.org/">OpenMoji</a>
                    </div>
                    <div>
                        License: <a href="https://creativecommons.org/licenses/by-sa/4.0/#">CC BY-SA 4.0</a>
                    </div>
                </div>

                <div>
                    <div className="text-body-emphasis">
                        Monochrome interface icons by <a href="https://fontawesome.com/license/free">Font Awesome</a>
                    </div>
                    <div>
                        License: <a href="https://creativecommons.org/licenses/by-sa/4.0/#">CC BY-SA 4.0</a>
                    </div>
                </div>

            </Stack>

        </Container>
    );
}

// gyoza/src/routes/about/+page.svelte
<script>
    import svgPurpleHeart from "$lib/site/purple-heart.svg";
</script>

<svelte:head>
    <title>About</title>
    <meta name="description" content="What in the world is izakaya.dev?" />
</svelte:head>

<main class="max-w-7xl mx-auto flex flex-col p-4">
    <section>
        <div>
            What is this website?
            <a href="https://github.com/ruksi/izakaya">
                TL;DR: a playground project
            </a>
        </div>
        <div>
            Made with
            <div class="inline-flex align-middle">
                <picture>
                    <img
                        src={svgPurpleHeart}
                        alt="love"
                        title="love"
                        height="24"
                        width="24"
                    />
                </picture>
            </div>
            by <a href="https://ruk.si/">Ruksi</a>
        </div>
        <div>
            License:
            <a href="https://github.com/ruksi/izakaya/blob/main/LICENSE">
                MIT
            </a>
        </div>
    </section>

    <section>
        <div class="text-zinc-50">
            Multicolor emojis by
            <a href="https://openmoji.org/">OpenMoji</a>
        </div>
        <div>
            License:
            <a href="https://creativecommons.org/licenses/by-sa/4.0/#">
                CC BY-SA 4.0
            </a>
        </div>
    </section>

    <section>
        <div class="text-zinc-50">
            Monochrome interface icons by
            <a href="https://fontawesome.com/license/free">
                Font Awesome
            </a>
        </div>
        <div>
            License:
            <a href="https://creativecommons.org/licenses/by-sa/4.0/#">
                CC BY-SA 4.0
            </a>
        </div>
    </section>
</main>

<style lang="postcss">
    section {
        @apply mb-4;
    }
    a {
        @apply text-stone-400
    }
</style>
